name: Impute
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _openmp_mutex=4.5
  - aom=3.9.1
  - bcftools=1.22
  - brotli=1.2.0
  - brotli-bin=1.2.0
  - bzip2=1.0.8
  - c-ares=1.34.6
  - ca-certificates=2025.11.12
  - cairo=1.18.4
  - click=8.3.1
  - coloredlogs=15.0.1
  - contourpy=1.3.3
  - cycler=0.12.1
  - cyvcf2=0.31.4
  - dav1d=1.2.1
  - fontconfig=2.15.0
  - fonttools=4.61.1
  - freetype=2.14.1
  - fribidi=1.0.16
  - graphite2=1.3.14
  - gsl=2.7
  - harfbuzz=10.2.0
  - htslib=1.22.1
  - humanfriendly=10.0
  - icu=73.2
  - jpeg=9e
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lcms2=2.17
  - lerc=4.0.0
  - libavif=1.3.0
  - libavif16=1.3.0
  - libblas=3.11.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcblas=3.11.0
  - libcurl=8.17.0
  - libcxx=21.1.7
  - libdeflate=1.22
  - libedit=3.1.20250104
  - libev=4.33
  - libexpat=2.7.3
  - libffi=3.5.2
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libglib=2.86.3
  - libiconv=1.18
  - libintl=0.25.1
  - liblapack=3.11.0
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libmpdec=4.0.0
  - libnghttp2=1.67.0
  - libopenblas=0.3.30
  - libopenjpeg=2.5.4
  - libpng=1.6.53
  - libsqlite=3.51.1
  - libssh2=1.11.1
  - libtiff=4.7.1
  - libwebp-base=1.6.0
  - libzlib=1.3.1
  - llvm-openmp=21.1.7
  - matplotlib=3.10.8
  - matplotlib-base=3.10.8
  - munkres=1.1.4
  - ncurses=6.5
  - numpy=2.3.5
  - openjdk=17.0.17
  - openssl=3.6.0
  - packaging=25.0
  - pandas=2.3.3
  - pcre2=10.47
  - perl=5.32.1
  - pillow=12.0.0
  - pip=25.3
  - pixman=0.46.4
  - plink=1.90b7.7
  - pyparsing=3.2.5
  - python=3.11.14
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.3
  - python_abi=3.11
  - pytz=2025.2
  - qhull=2020.2
  - rav1e=0.7.1
  - readline=8.2
  - scipy=1.16.3
  - setuptools=80.9.0
  - six=1.17.0
  - svt-av1=3.1.2
  - tabix=1.11
  - tk=8.6.13
  - tornado=6.5.4
  - tzdata=2025b
  - unicodedata2=17.0.0
  - wheel=0.45.1
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - zlib=1.3.1
  - zstd=1.5.7
prefix: /opt/anaconda3/envs/Impute
